### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by FroggerHH** [Delitel-WEB/YandexMusicDiscordRpc#1]
Только поменял токены на свои и ловлю ошибку. Насколько понимаю не получается подключится к дискорд боту

![изображение](https://github.com/Delitel-WEB/YandexMusicDiscordRpc/assets/86151874/8f844b05-fb1e-4e98-8e4b-736fcd416709)

`Log: `
```bash
Yandex Music API v2.0.1, Copyright (C) 2019-2022 Il`ya (Marshal) <https://github.com/MarshalX>
Licensed under the terms of the GNU Lesser General Public License v3 (LGPLv3)

Traceback (most recent call last):
  File "/home/jf/Документы/GitHub/YandexMusicDiscordRpc/main.py", line 12, in <module>
    rpc.connect()
  File "/home/jf/.local/lib/python3.12/site-packages/pypresence/presence.py", line 43, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jf/.local/lib/python3.12/site-packages/pypresence/baseclient.py", line 107, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/unix_events.py", line 261, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 659, in _sock_connect
    sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Delitel-WEB** [comment]
Не удаётся установить связь с приложением дискорда.

**Comment by FroggerHH** [comment]
С другой библиотекой для дискорда работает
